version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=vpp_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=vpp
      - MYSQL_PASSWORD=vpp
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local