server:
  port: 8080

spring:
  application:
    name: vpp
  datasource:
    url: jdbc:postgresql://localhost:5433/vpp_db?rewriteBatchedStatements=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        generate_statistics: true
        jdbc:
          batch_size: 50

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  maxPostcodesInQuery: 50

  # database or stream
  # database performs well for large dataset
  # stream processes the collection in 3 streams
  batteryQueryStrategy: database