server:
  port: 8080

spring:
  application:
    name: vpp
  datasource:
    url: jdbc:mysql://localhost:3307/vpp_db
    username: vpp
    password: vpp
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  maxPostcodesInQuery: 50

  # database or stream
  # database performs well for large dataset
  # stream processes the collection in 3 streams
  batteryQueryStrategy: database