server:
  port: 8080

spring:
  application:
    name: vpp
  datasource:
    url: jdbc:mysql://localhost:3306/vpp_db
    username: vpp
    password: vpp
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always  # Optional: auto-runs schema.sql or data.sql if present

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
